export const VERSION = 'v1.1';

export const CHANGELOG = [
  { version: 'v1.1',
    why: 'Sometimes you just want to hide all the happy hours.',
    changes: [
      'Exclude keywords filter: type a word, press Enter, and matching events disappear',
      'Add multiple keywords as chips, click × to remove',
      'Excluded keywords are saved between visits',
    ]},
  { version: 'v1.0',
    why: 'Switched from showing all events to only daily new additions. Less noise, more signal.',
    changes: [
      'Now shows only newly added events since the last daily check',
      'Added subtitle explaining the page scope, plus a "Why?" explainer',
      'Shows refresh schedule next to the last-checked timestamp',
      'Filters out events that already started (tomorrow onward only)',
      'Expanded event range from 1 week to several months ahead',
    ]},
  { version: 'v0.9',
    why: 'Visual polish: better icons, tighter headings, cleaner layout.',
    changes: [
      'Replaced emoji icons with crisp inline SVGs (calendar, pin, users)',
      'Calendar columns now have visible day separators',
      'Tighter line-height on headings for better visual hierarchy',
    ]},
  { version: 'v0.8',
    why: 'Too many font sizes doing the same job. Time for spring cleaning.',
    changes: [
      'Simplified font sizes from 6 levels to 5 (less is more)',
      'Price filter: removed "All" button, just click again to deselect',
      'Calendar switched to 24-hour time across all languages',
      'Search placeholder now shows example keywords',
    ]},
  { version: 'v0.7',
    why: 'The location list was getting out of hand with 25+ cities showing at once.',
    changes: [
      'Location pills now collapse to 2 rows, click "More" to see the rest',
      'Most popular cities show first',
      'Cleaner calendar time labels (just the number, no ":00")',
      'Calendar only shows 8 AM – 10 PM (nobody\'s going to events at 3 AM… right?)',
      'Added this version changelog popup',
    ]},
  { version: 'v0.6',
    why: 'Some text was too faint to read comfortably. Accessibility matters.',
    changes: [
      'Made all text easier to read with better contrast',
      'Set a minimum text size so nothing is too tiny',
      'Consistent text styling across the whole page',
    ]},
  { version: 'v0.5',
    why: 'Hard to tell which days are busiest just by scrolling through a list.',
    changes: [
      'Added a calendar heatmap (darker = more events)',
      'Scroll sideways to see the whole week',
      'Click a time slot to jump straight to those events',
    ]},
  { version: 'v0.4',
    why: '200+ events in a flat list was… a lot.',
    changes: [
      'Events grouped by day with date headers',
      'Shows total event count at the top',
      'Cleaned up location names (bye bye ", California")',
    ]},
  { version: 'v0.3',
    why: 'Scrolling through hundreds of events to find one? No thanks.',
    changes: [
      'Search bar to find events by name or host instantly',
      'Filter pills show how many events match each option',
      'Your filter preferences are remembered between visits',
    ]},
  { version: 'v0.2',
    why: 'A raw list of events isn\'t very useful without ways to filter and sort.',
    changes: [
      'Filter by price: Free or Paid',
      'Filter by location, pick one or several cities',
      'Sort by time, name, or guest count',
    ]},
  { version: 'v0.1',
    why: 'Bay Area tech events were scattered across the internet. Why not put them in one place?',
    changes: [
      'Event listing page pulling from Luma automatically',
      'Each event shows title, date, location, price, and guest count',
      'New events fetched daily',
      'Available in English and Chinese',
    ]},
];
